<?php

use Ballybran\Library\Form;

?>
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-8 text-left"> 
      <h1>Welcome</h1>
      <hr>
              <?php
              echo Form::open(['action'=>URL. 'user/login', 'method'=> 'post']);
              echo Form::input(['type'=>'text', 'name'=>'email', 'placeholder'=> 'insert you email']);
              echo Form::input(['type'=>'password', 'name'=>'password', 'placeholder'=> 'insert you password']);
              echo Form::submit(['type'=>'submit', 'value'=>'Login']);
              echo Form::close();

              ?>
    </div>
      <div class="col-sm-2 sidenav">
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

